### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [tuxfy/JammmingReact#2]
### Criteria 1: App Creation, Folder Structure, and File Paths
* _Score Level:_ 4/4
* _Comment(s):_ The architectural structure of the project was in line with best practice measures. 
 
### Criteria 2: Correct Implementation of User Flows
* _Score Level:_ 4/4
* _Comment(s):_ The flow for the request API's were done very well.
 
### Criteria 3: Proper JavaScript and JSX Syntax and Formatting
* _Score Level:_ 4/4
* _Comment(s):_ The syntax was nicely formatted and indented. 
 
### Criteria 4: Implementation Adheres to DRY Principles
* _Score Level:_ 4/4
* _Comment(s):_ The code structure was concise and modular. 
 
### Overall Score: 16/16 

The necessary features required were executed very well. The additional features requires some pruning.

**Comment by tuxfy** [comment]
Thank you very much you for this!
Can you precise this point "Only the playlist tracks were not saved on 'save playlist'." of criteria 2, please? I want to fix this :)

**Comment by mp1pro** [comment]
That was an error, sorry. Its fine.

**Comment by tuxfy** [comment]
No problem. Thank you :)
